-- Total Revenue
-- Total Revenue by month per category
-- Total Number of Customers
-- Number of customers by month
-- Total Sales by Product
-- Total Revenue by Product
-- Busiest Days
-- Busiest Months
-- Busiest Time of day
-- Total Sales by Product Type
-- Total Revenue By Product Type
-- Total Sales by product category
-- Total Revenue by product category
